### PR TITLE
join community

### PR DESCRIPTION
**Pull request by creatix**
@LiorRabin  Tal told me you are working on the join community transaction.
I have already copied @leonprou code and its not working
A problem with the ABI probably

### CODE REVIEW

**Comment by leonprou** [comment]
@LiorAgnin FYI :sweat_smile:

**Comment by leonprou** [comment]
@creatix Yeah you should use a community contract ABI that I attached in Monday

**Comment by LiorAgnin** [comment]
I'll continue from here, thanks.

**Comment by LiorRabin** [comment]
@creatix We can/should merge this to master?

**Comment by leonprou** [comment]
@creatix @LiorRabin I think the join community isn't finished, but Eli fixed the sending  problem here.

**Comment by LiorRabin** [comment]
That's why I asked...

**Comment by creatix** [comment]
So merge it?

**Comment by creatix** [comment]
So yeah let’s merge

**Pull request merged**
